In [1]:
import sys
sys.path.append('../src/APL_to_python')
from simple_algo_utils import *
import numpy as np

There will be minimal description here as this is supplementary to "Get Started.docx", where most of the descriptions are.

# Illustrative Example

In [2]:
J = np.array([ [1,0], [0,1], [-1,0], [0,-1]])
nBSG = 4
Nj = 4
BSG=setBSG(nBSG, Nj)
P = 1
ALPH=' ABCDEFGHIJKLMNOPQRSTUVWXYZ'
print('BSG\n',BSG)
print('topology\n',J)

BSG
 [[1 2 3 4]
 [4 1 2 3]
 [3 4 1 2]
 [2 3 4 1]]
topology
 [[ 1  0]
 [ 0  1]
 [-1  0]
 [ 0 -1]]


In [3]:
L = 5
age = np.zeros(shape=(L,L))
CE = np.ones(shape=(L,L))
CE[2,2]=5
G0 = np.array([[0,0,0,0],[1,2,3,4],[2,0,2,0],[3,0,3,0],[4,0,4,0]])
GE = setEXTG0(nBSG, G0, Nj, BSG)

T_MAX = 3
develop(T_MAX, 
    Nj, nBSG, L, J, GE, CE, age,
    P, verbose=200)

ITERATION:1
T:0
CE (before growth):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
ENV:
[[[0. 0. 0. 0. 0.]
  [0. 0. 3. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 4. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 2. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
D, stores bond values, including the ones not in CHANGED (later discarded)
 [[0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 4. 0. 2. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
E, stores neighbor indices, including the ones not in CHANGED (later discarded)
 [[0 0 0 0 0]
 [0 0 1 0 0]
 [0 2 0 4 0]
 [0 0 3 0 0]
 [0 0 0 0 0]]
CHANGE
 [[0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
D * CHANGE
 [[0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 4. 0. 2. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 

# Illustrative Example Revised

After observing the unnatural directions, we refine the python code so that topology matrix matches the direction of the growth. This is indicated by using 'revised' for COMPENV_MODE 

In [4]:
L = 5
age = np.zeros(shape=(L,L))
CE = np.ones(shape=(L,L))
CE[2,2]=5
G0 = np.array([[0,0,0,0],[1,2,3,4],[2,0,2,0],[3,0,3,0],[4,0,4,0]])
GE = setEXTG0(nBSG, G0, Nj, BSG)

print('G0\n',G0)
print('GE\n',GE)

T_MAX = 3
develop(T_MAX, 
    Nj, nBSG, L, J, GE, CE, age,
    P, verbose=200, COMPENV_MODE='revised',ALPH=ALPH)

G0
 [[0 0 0 0]
 [1 2 3 4]
 [2 0 2 0]
 [3 0 3 0]
 [4 0 4 0]]
GE
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 2. 3. 4.]
 [4. 1. 2. 3.]
 [3. 4. 1. 2.]
 [2. 3. 4. 1.]
 [2. 0. 2. 0.]
 [0. 2. 0. 2.]
 [2. 0. 2. 0.]
 [0. 2. 0. 2.]
 [3. 0. 3. 0.]
 [0. 3. 0. 3.]
 [3. 0. 3. 0.]
 [0. 3. 0. 3.]
 [4. 0. 4. 0.]
 [0. 4. 0. 4.]
 [4. 0. 4. 0.]
 [0. 4. 0. 4.]]
ITERATION:1
T:0
CE (before growth):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
ENV:
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 2. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 4. 0. 0.]
  [0. 0. 0. 0. 0.]]]
D, stores bond values, including the ones not in CHANGED (later discarded)
 [[0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0