In [1]:
import sys
sys.path.append('../src/APL_to_python')
from simple_algo_utils import *
import numpy as np

There will be minimal description here as this is supplementary to "Get Started.docx", where most of the descriptions are.

## CODE
Python version of CODE from textbook p.198.

In [2]:
x = np.array(range(1,1+4)).reshape(2,2)
y = np.array(range(1,1+4)).reshape(2,2)*2
print(code_generator(x,y,4))

[[ 2  8]
 [14 20]]


## COMPENV
Python version of COMPENV from textbook p.199. 

In [3]:
Nj = 4
L = 5
J = np.array([ [1,0], [0,1], [-1,0], [0,-1]])
GE = np.array(range(32)).reshape(8,4)+1
CE = np.ones(shape=(L,L))
CE[2,1]=5
print('GE\n',GE)
print('CE\n',CE)
print('\nENV')
print(compenv(Nj, L, J, GE, CE))

GE
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
CE
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 5. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

ENV
[[[ 3.  3.  3.  3.  3.]
  [ 3. 19.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.]
  [ 3.  3.  3.  3.  3.]]

 [[ 4.  4.  4.  4.  4.]
  [ 4.  4.  4.  4.  4.]
  [20.  4.  4.  4.  4.]
  [ 4.  4.  4.  4.  4.]
  [ 4.  4.  4.  4.  4.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1. 17.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.]
  [ 2.  2. 18.  2.  2.]
  [ 2.  2.  2.  2.  2.]
  [ 2.  2.  2.  2.  2.]]]


## GROWTH1
Python version of COMPENV from textbook p.205. 

In [4]:
nBSG = 4
L = 5
Nj = 4
age = np.zeros(shape=(L,L))
ENV = np.zeros(shape=(Nj,L,L))
ENV[0,1,1] = ENV[1,2,2] = ENV[3,1,2] = 2
CE = np.ones(shape=(L,L))
CE[1,2]=5

print('ENV\n',ENV)
print('CE\n',CE)
print('GROWTH1')
B, age = growth1(CE, age, ENV, nBSG, Nj)
print('B\n',B)
print('age\n',age)

ENV
 [[[0. 0. 0. 0. 0.]
  [0. 2. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 2. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 2. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
CE
 [[1. 1. 1. 1. 1.]
 [1. 1. 5. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
GROWTH1
B
 [[1. 1. 1. 1. 1.]
 [1. 5. 5. 1. 1.]
 [1. 1. 6. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
age
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## COMPNONZERO
Python version of COMPENV from textbook p.200

In [5]:
import numpy as np
M = np.zeros(shape=(5,5))
M[0,2] = M[1,0] = M[1,3] = 2
M[2,1] = M[2,4] = 2
M[3,2] = M[4,0] = M[4,3] = 2
print(M)
Z, V1, V2=compnonzero(M)
Z

[[0. 0. 2. 0. 0.]
 [2. 0. 0. 2. 0.]
 [0. 2. 0. 0. 2.]
 [0. 0. 2. 0. 0.]
 [2. 0. 0. 2. 0.]]


array([[0., 0., 2., 0., 0.],
       [2., 0., 0., 2., 0.],
       [0., 2., 0., 0., 2.],
       [0., 0., 2., 0., 0.],
       [2., 0., 0., 2., 0.]])

In [6]:
M = np.zeros(shape=(4,3))
M[:,1] = 1
print(M)
Z, V1, V2=compnonzero(M)
Z

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


array([[1.],
       [1.],
       [1.],
       [1.]])

In [7]:
M[0,0]=3
print(M)
Z, V1, V2=compnonzero(M)
Z

[[3. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


array([[3., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

## DEVELOP
Python version of DEVELOP from textbook p.200

In [8]:
L = 5
age = np.zeros(shape=(L,L))
CE = np.ones(shape=(L,L))
CE[3,3]=5
G0 = np.array([[0,0,0,0],[2,0,2,0]])
nBSG = 4
Nj = 4
BSG=setBSG(nBSG, Nj)
GE = setEXTG0(nBSG, G0, Nj, BSG)
P = 1

T_MAX = 3
develop(T_MAX, 
    Nj, nBSG, L, J, GE, CE, age,
    P, verbose=0)

ITERATION:1
After growth:
A
A
A
ITERATION:2
After growth:
A
A
A
A
A
ITERATION:3
After growth:
A
A
A
A
A
